Arguments: 
  /Users/nytoair/.nvm/versions/node/v16.15.1/bin/node /Users/nytoair/.nvm/versions/node/v16.15.1/bin/yarn add nodemone

PATH: 
  /Users/nytoair/google-cloud-sdk/bin:/Users/nytoair/.pyenv/shims:/Users/nytoair/.nvm/versions/node/v16.15.1/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/nytoair/google-cloud-sdk/bin:/Users/nytoair/.nvm/versions/node/v16.15.1/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin

Yarn version: 
  1.22.18

Node version: 
  16.15.1

Platform: 
  darwin arm64

Trace: 
  Error: https://registry.yarnpkg.com/nodemone: Not found
      at Request.params.callback [as _callback] (/Users/nytoair/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:66138:18)
      at Request.self.callback (/Users/nytoair/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:140883:22)
      at Request.emit (node:events:527:28)
      at Request.<anonymous> (/Users/nytoair/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:141855:10)
      at Request.emit (node:events:527:28)
      at IncomingMessage.<anonymous> (/Users/nytoair/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:141777:12)
      at Object.onceWrapper (node:events:641:28)
      at IncomingMessage.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm manifest: 
  {
    "name": "run_my_tests",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
